<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/04/06 19:51:55
$this->security = array (
  'edit' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
