<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/04/06 22:33:52

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=kendafrik',
  'username' => 'root',
  'password' => 'iloveumomdad4a',
  'name' => 'doctrine',
)),);
