<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/04/06 22:33:52
sfConfig::add(array(
  'app_recaptcha_public_key' => '6LcWDcMSAAAAABW0hFXkroNjMjaXJoRuOBXlQjKJ',
  'app_recaptcha_private_key' => '6LcWDcMSAAAAAO97sjj765Xgw4aGP_du1kfrKcMa',
  'app_facebook_app_id' => '122377107838770',
  'app_facebook_api_key' => 'd28afb2b25babbcdb3bf6a2950bfaf45',
  'app_facebook_secret' => 'e091c939f922c71a729fe9a339adffb2',
  'app_facebook_base_url' => 'http://www.islamside.com.localhost/',
  'app_facebook_app_url' => 'http://islamside.com.localhost',
));
