Category:
  actAs:
    Timestampable: ~
    I18n:
      fields: [name]
      actAs:
        Sluggable: { fields: [name], uniqueBy: [lang, name] }      
  columns:
    name: { type: string(255), notnull: true }
 
Ken:
  actAs: { Timestampable: ~ }
  columns:
    category_id:  { type: integer, notnull: true }

    type:         { type: string(255) }    ##Vente achat location
    objet:        { type: string(255) }    ##iphone 4g...
    etat:         { type: string(255) }    ##neuf, endomage, tres endomage

    prix:         { type: int }            ##20000
    devise:       { type: string(255) }    ##dirham    
    debattre:     { type: string(255) }    ##A debattre / prix fixe
    
    pays:         { type: string(255) }
    ville:        { type: string(255) }    
    
    email:        { type: string(255) }
    tel1:         { type: string(255) }    
    tel2:         { type: string(255) }        
    
    supplement:   { type: string(4000) }       
    
    image:        { type: string(255) }
    is_activated: { type: boolean, notnull: true, default: 1 }
  relations:
    Category: { onDelete: CASCADE, local: category_id, foreign: id, foreignAlias: Kens } 
